### ISSUE TITLE
EMS: alert icons show as black boxes on Chrome

### ISSUE THREAD

**Issue by fwextensions** [sfbrigade/bats-server#192]
Not sure if this ever worked, or a recent PR messed it up on dev:

![image](https://user-images.githubusercontent.com/61631/181669324-6400af86-cfe5-4714-a120-88c10305cff2.png)

This is in Chrome 103 on Windows.

It seems like a webkit prefix is still required for the mask to work, despite the `@supports` directive.  Changing it to `-webkit-mask` makes the icon appear:

```css
@supports (mask: url(""))
.usa-alert--warning:before {
    background: none;
    background-color: #1b1b1b;
    mask: url(./img/usa-icons/warning.svg) no-repeat center/contain;
}
```
